# Generated by Django 3.2.6 on 2023-05-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='is_active',
        ),
    ]
